[package]
name = "zvault"
version = "0.1.0"
authors = ["Dennis Schwerdel <schwerdel@informatik.uni-kl.de>"]
description = "Deduplicating backup tool"

[dependencies]
serde = "0.9"
rmp-serde = "0.12"
serde_yaml = "0.6"
serde_utils = "0.5.1"
squash-sys = "0.9"
mmap = "*"
quick-error = "1.1"
blake2-rfc = "*"
murmurhash3 = "*"
rustc-serialize = "0.3"
chrono = "0.3"
clap = "2.19"
log = "0.3"
byteorder = "1.0"
ansi_term = "0.9"
sodiumoxide = "*"
libc = "*"

[build-dependencies]
pkg-config = "0.3"
