[package]
name = "zvault"
version = "0.1.0"
authors = ["Dennis Schwerdel <schwerdel@googlemail.com>"]
description = "Deduplicating backup tool"

[dependencies]
serde = "0.9"
rmp-serde = "0.12"
serde_yaml = "0.6"
serde_utils = "0.5.1"
squash-sys = "0.9"
mmap = "0.1"
quick-error = "1.1"
blake2-rfc = "0.2"
murmurhash3 = "0.0.5"
rustc-serialize = "0.3"
chrono = "0.3"
clap = "2.22"
log = "0.3"
byteorder = "1.0"
ansi_term = "0.9"
sodiumoxide = "0.0.14"
filetime = "0.1"
regex = "0.2"
fuse = "0.3"
lazy_static = "0.2"
rand = "0.3"
tar = "0.4"
xattr = "0.1"
crossbeam = "0.2"
pbr = "1.0.0-alpha.3"
time = "*"
libc = "*"

[build-dependencies]
pkg-config = "0.3"
